# Generated by Django 5.2.9 on 2026-01-05 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was soft-deleted', null=True)),
                ('device_id', models.CharField(db_index=True, help_text='Unique device identifier (MAC, serial number, etc.)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable device name', max_length=255)),
                ('device_type', models.CharField(choices=[('temperature', 'Temperature Sensor'), ('humidity', 'Humidity Sensor'), ('pressure', 'Pressure Sensor'), ('motion', 'Motion Detector'), ('light', 'Light Sensor'), ('custom', 'Custom Sensor')], help_text='Type of sensor device', max_length=50)),
                ('location', models.CharField(help_text='Physical location of device', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude', max_digits=9, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether device is actively reporting')),
                ('last_reading_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of last received reading', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional device configuration (firmware version, etc.)')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device_type', 'is_active'], name='sensors_dev_device__f65c89_idx'), models.Index(fields=['deleted', 'is_active'], name='sensors_dev_deleted_c0c5f5_idx'), models.Index(fields=['last_reading_at'], name='sensors_dev_last_re_9aa78d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SensorAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('bucket', models.CharField(choices=[('5min', '5 Minutes'), ('1hour', '1 Hour'), ('1day', '1 Day')], help_text='Aggregation time bucket', max_length=10)),
                ('bucket_start', models.DateTimeField(db_index=True, help_text='Start timestamp of this bucket')),
                ('bucket_end', models.DateTimeField(help_text='End timestamp of this bucket')),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, help_text='Minimum value in bucket', max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, help_text='Maximum value in bucket', max_digits=10, null=True)),
                ('avg_value', models.DecimalField(blank=True, decimal_places=4, help_text='Average value in bucket', max_digits=10, null=True)),
                ('count', models.PositiveIntegerField(default=0, help_text='Total readings in bucket')),
                ('valid_count', models.PositiveIntegerField(default=0, help_text='Valid readings in bucket')),
                ('device', models.ForeignKey(help_text='Device being aggregated', on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', to='sensors.device')),
            ],
            options={
                'verbose_name': 'Sensor Aggregate',
                'verbose_name_plural': 'Sensor Aggregates',
                'ordering': ['-bucket_start'],
                'indexes': [models.Index(fields=['device', 'bucket', 'bucket_start'], name='sensors_sen_device__68e687_idx'), models.Index(fields=['bucket_start', 'bucket_end'], name='sensors_sen_bucket__87d0c5_idx')],
                'unique_together': {('device', 'bucket', 'bucket_start')},
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('value', models.DecimalField(decimal_places=4, help_text='Sensor measurement value', max_digits=10)),
                ('unit', models.CharField(blank=True, default='', help_text='Unit of measurement (°C, %, hPa, etc.)', max_length=20)),
                ('is_valid', models.BooleanField(db_index=True, default=True, help_text='Whether reading passed validation')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional reading data (raw value, RSSI, etc.)')),
                ('device', models.ForeignKey(help_text='Device that generated this reading', on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.device')),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'created_at'], name='sensors_sen_device__c87984_idx'), models.Index(fields=['created_at', 'is_valid'], name='sensors_sen_created_88f0e8_idx'), models.Index(fields=['is_valid'], name='sensors_sen_is_vali_6f09bc_idx')],
            },
        ),
    ]
