# Generated by Django 5.2.9 on 2026-01-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="tenant_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Tenant identifier for multi-tenancy",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sensoraggregate",
            name="tenant_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Tenant identifier for multi-tenancy",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sensorreading",
            name="tenant_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Tenant identifier for multi-tenancy",
                null=True,
            ),
        ),
    ]
