# Generated by Django 5.2.9 on 2026-01-05 11:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='When this record was soft-deleted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('order_number', models.CharField(db_index=True, help_text='Unique order number (e.g., ORD-20250105-001)', max_length=50, unique=True)),
                ('customer_email', models.EmailField(help_text='Customer email address', max_length=254)),
                ('customer_name', models.CharField(help_text='Customer name', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', help_text='Current order status', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of line items before tax and shipping', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Shipping cost', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount or coupon amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final total: subtotal + tax + shipping - discount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('shipping_address', models.TextField(help_text='Full shipping address')),
                ('billing_address', models.TextField(blank=True, help_text='Billing address (if different from shipping)')),
                ('notes', models.TextField(blank=True, help_text='Internal notes or customer comments')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional order data (source, campaign, etc.)')),
                ('fulfilled_at', models.DateTimeField(blank=True, db_index=True, help_text='When order was fulfilled', null=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'), models.Index(fields=['customer_email', 'status'], name='orders_orde_custome_66d5e2_idx'), models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'), models.Index(fields=['fulfilled_at'], name='orders_orde_fulfill_c54023_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('product_name', models.CharField(help_text='Product name (snapshot from order time)', max_length=255)),
                ('product_sku', models.CharField(blank=True, help_text='Product SKU', max_length=100)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity ordered', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at order time', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='quantity × unit_price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional item data (attributes, options, etc.)')),
                ('order', models.ForeignKey(help_text='Parent order', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Line Item',
                'verbose_name_plural': 'Order Line Items',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['order'], name='orders_orde_order_i_65d534_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Unique key for idempotent retries', max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', help_text='Currency code (ISO 4217)', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current payment status', max_length=20)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('stripe', 'Stripe'), ('other', 'Other')], help_text='Payment method used', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Payment processor transaction ID', max_length=255)),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='Number of payment attempts')),
                ('last_error', models.TextField(blank=True, help_text='Error message from last failed attempt')),
                ('authorized_at', models.DateTimeField(blank=True, help_text='When payment was authorized', null=True)),
                ('captured_at', models.DateTimeField(blank=True, help_text='When payment was captured (charged)', null=True)),
                ('failed_at', models.DateTimeField(blank=True, help_text='When payment failed', null=True)),
                ('refunded_at', models.DateTimeField(blank=True, help_text='When payment was refunded', null=True)),
                ('order', models.OneToOneField(help_text='Associated order', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='orders_paym_order_i_8c8d98_idx'), models.Index(fields=['status'], name='orders_paym_status_83f434_idx'), models.Index(fields=['idempotency_key'], name='orders_paym_idempot_327aa2_idx'), models.Index(fields=['created_at', 'status'], name='orders_paym_created_576fa6_idx')],
            },
        ),
    ]
