# Generated by Django 5.2.9 on 2026-01-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_tenant_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="orders_paym_order_i_8c8d98_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="orders_paym_status_83f434_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="orders_paym_idempot_327aa2_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="orders_paym_created_576fa6_idx",
        ),
        migrations.AddField(
            model_name="orderlineitem",
            name="tenant_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Tenant identifier for multi-tenancy",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="tenant_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Tenant identifier for multi-tenancy",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["created_at"], name="orders_paym_created_4b0957_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["updated_at"], name="orders_paym_updated_8999e1_idx"),
        ),
    ]
