[metadata]
name = django-data-intensive-systems
version = 0.1.0

[options]
packages = find:
python_requires = >=3.13
include_package_data = True

[options.packages.find]
include =
    apps*
    config*
exclude =
    logs*
    staticfiles*
    media*
    tests*

[options.package_data]
* = templates/*.html, static/*.css, static/*.js, locale/*

[flake8]
max-line-length = 100
extend-ignore =
    E203
    E261
    E302
    E303
    E305
    E501
    F401
    F405
    F841
    W291
    W292
    W293
    W391